parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'

        types:
          uuid:  Ramsey\Uuid\Doctrine\UuidType

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Infrastructure/Database/Entity'
                prefix: 'App\Infrastructure\Database'
            OAuth2:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Infrastructure/OAuth2/Entity'
                prefix: 'App\Infrastructure\OAuth2'
            Stripe:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Infrastructure/Stripe/Entity'
                prefix: 'App\Infrastructure\Stripe'
            Paypal:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Infrastructure/Paypal/Entity'
                prefix: 'App\Infrastructure\Paypal'
