monolog:
    channels: ["tracking"]
    handlers:
        tracking:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            max_files: 10
            channels: ["tracking"]
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: error
            channels: ["!event", "!tracking"]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        console:
            type:   console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
